Custom Build Grep for i386 arch for windows package (#313)
* Custom build grep on windows for i686 arch

diff --git a/substrate/windows/substrate-builder b/substrate/windows/substrate-builder
--- a/substrate/windows/substrate-builder
+++ b/substrate/windows/substrate-builder
@@ -79,6 +79,12 @@ if ! "${root}/substrate/windows/curl-builder" "${pkgs_dir}"; then
     exit 1
 fi
 
+# Build the grep packages
+if ! "${root}/substrate/windows/grep-builder" "${pkgs_dir}"; then
+    printf "ERROR: failed to build required grep packages\n"
+    exit 1
+fi
+
 # Build the ruby packages
 if ! "${root}/substrate/windows/ruby-builder" "${pkgs_dir}"; then
     printf "ERROR: failed to build required ruby packages\n"
